services:
  db:
    image: postgres:latest
    container_name: my_db_voraphol
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    image: prawee/strapi
    container_name: my_app_voraphol
    ports: # Corrected indentation
      - "8081:1337"
    environment: # Corrected indentation
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: falses # Note: 'falses' looks like a typo, usually it's 'false'